apiVersion: v1
kind: PersistentVolume
metadata:
        name: pv-vol
        labels:
                type: local
spec:
        storageClassName: manual
        capacity:
                storage: 3Gi
        accessModes:
                - ReadWriteOnce
        hostPath:
                path: "/mnt/data"
