apiVersion: v1
kind: Pod
metadata:
  name: high-pod
spec:
  containers:
    - name: high-container
      image: tomcat:7
      resources:
        requests:
          memory: "300M"
          cpu: "10m"
        limits:
          memory: "300M"
          cpu: "10m"
  priorityClassName: high
