apiVersion: v1
kind: Pod
metadata:
        name: secret-pod
spec:
        containers:
                - name: secret-container
                  image: tomcat:7
                  ports:
                          - containerPort: 8080
                            name: app-srv
                  env:
                          - name: credentials
                            valueFrom:
                                    secretKeyRef:
                                            name: mypass
                                            key: password
