apiVersion: v1
kind: Pod
metadata:
        name: secret-pod-vol
spec:
        containers:
                - name: secret-vol-container
                  image: tomcat:7
                  ports:
                          - containerPort: 8080
                            name: app-srv-vol
                  volumeMounts:
                          - name: password
                            mountPath: "/mnt"
                            readOnly: true
        volumes:
                - name: password
                  secret:
                          secretName: mypass
